# Generated by Django 6.0.5 on 2026-05-24 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='provider',
            field=models.CharField(choices=[('mercadopago', 'Mercado Pago')], max_length=20),
        ),
    ]
