# Generated by Django 6.0.5 on 2026-09-03 23:52

import apps.accounts.models
import apps.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_verify_existing_emails"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.accounts.models.avatar_upload_path,
                validators=[apps.accounts.validators.validate_avatar],
            ),
        ),
    ]
