/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [
        "templates/**/*.html",
        "apps/**/templates/**/*.html",
    ],
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "primary": "#00685f",
                "on-primary": "#ffffff",
                "primary-container": "#008378",
                "on-primary-container": "#f4fffc",
                "primary-fixed": "#89f5e7",
                "primary-fixed-dim": "#6bd8cb",
                "on-primary-fixed": "#00201d",
                "on-primary-fixed-variant": "#005049",
                "inverse-primary": "#6bd8cb",
                "secondary": "#505f76",
                "on-secondary": "#ffffff",
                "secondary-container": "#d0e1fb",
                "on-secondary-container": "#54647a",
                "secondary-fixed": "#d3e4fe",
                "secondary-fixed-dim": "#b7c8e1",
                "on-secondary-fixed": "#0b1c30",
                "on-secondary-fixed-variant": "#38485d",
                "tertiary": "#924628",
                "on-tertiary": "#ffffff",
                "tertiary-container": "#b05e3d",
                "on-tertiary-container": "#fffbff",
                "tertiary-fixed": "#ffdbce",
                "tertiary-fixed-dim": "#ffb59a",
                "on-tertiary-fixed": "#370e00",
                "on-tertiary-fixed-variant": "#773215",
                "error": "#ba1a1a",
                "on-error": "#ffffff",
                "error-container": "#ffdad6",
                "on-error-container": "#93000a",
                "background": "#f5faf8",
                "on-background": "#171d1c",
                "surface": "#f5faf8",
                "on-surface": "#171d1c",
                "surface-dim": "#d6dbd9",
                "surface-bright": "#f5faf8",
                "surface-variant": "#dee4e1",
                "on-surface-variant": "#3d4947",
                "surface-tint": "#006a61",
                "surface-container-lowest": "#ffffff",
                "surface-container-low": "#f0f5f2",
                "surface-container": "#eaefed",
                "surface-container-high": "#e4e9e7",
                "surface-container-highest": "#dee4e1",
                "inverse-surface": "#2c3130",
                "inverse-on-surface": "#edf2f0",
                "outline": "#6d7a77",
                "outline-variant": "#bcc9c6",
            },
            borderRadius: {
                DEFAULT: "0.25rem",
                lg: "0.5rem",
                xl: "0.75rem",
                full: "9999px",
            },
            spacing: {
                unit: "8px",
                gutter: "16px",
                "stack-sm": "8px",
                "stack-md": "16px",
                "stack-lg": "32px",
                "container-padding": "24px",
            },
            fontFamily: {
                display: ["Geist", "sans-serif"],
                h1: ["Geist", "sans-serif"],
                h2: ["Geist", "sans-serif"],
                h3: ["Geist", "sans-serif"],
                "label-md": ["Geist", "sans-serif"],
                "label-sm": ["Geist", "sans-serif"],
                "body-lg": ["Inter", "sans-serif"],
                "body-md": ["Inter", "sans-serif"],
                "body-sm": ["Inter", "sans-serif"],
            },
            fontSize: {
                display: ["36px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
                h1: ["30px", { lineHeight: "1.3", fontWeight: "600" }],
                h2: ["24px", { lineHeight: "1.3", fontWeight: "600" }],
                h3: ["20px", { lineHeight: "1.4", fontWeight: "600" }],
                "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
                "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
                "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
                "label-md": ["14px", { lineHeight: "1", letterSpacing: "0.01em", fontWeight: "500" }],
                "label-sm": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
            },
        },
    },
    plugins: [],
};
