# Generated by Django 6.0.5 on 2026-05-07 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proposals", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proposal",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="proposals",
                to="proposals.client",
            ),
        ),
    ]
