# Generated by Django 6.0.5 on 2026-05-22 01:29

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proposals", "0002_alter_proposal_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposal",
            name="estimated_hours",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AddField(
            model_name="proposal",
            name="hourly_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AddField(
            model_name="proposal",
            name="pricing_type",
            field=models.CharField(
                choices=[("fixed", "Fixed Price"), ("hourly", "Hourly Rate")],
                default="fixed",
                max_length=10,
            ),
        ),
    ]
