# Generated by Django 6.0.5 on 2026-05-22 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0003_pricing_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='pricing_type',
            field=models.CharField(choices=[('fixed', 'Fixed Price'), ('hourly', 'Hourly Rate')], db_default='fixed', default='fixed', max_length=10),
        ),
    ]
